version: "3.9"

services:
  
  streamer:
    build: streamer
    ports:
      - "9092:9092"

  producer:
    build: producer
    depends_on:
      - streamer
  
  predictor:
    build: predictor
    depends_on: 
      - streamer
      - producer